### ISSUE TITLE
Targeting when playing a healing routine.

### ISSUE THREAD

**Issue by Markeeen** [aevitas/BuddyWing.DefaultCombat#11]
Like title says, in its current form, trying to play a healing routine is next to impossible.

The targeting is all over the place and sometimes the routine (tried on Sorcerer Corruption) does not work at all.

I heard from people on the forums that they circumvent the problem by removing the targeting and doing it manually.

PureSwtor rotation seems to work for healing right now.

**Comment by aevitas** [comment]
Can you describe the behaviour the current targeting is displaying in a little more detail? Does it target the wrong targets, does it ignore the tank even though one is set, does it never properly target anything at all, etc?

This shouldn't be too hard to improve, given we know what's wrong with the current functionality, and where we would like it to be.

**Comment by Markeeen** [comment]
I will try and run a healing routine and will provide a log. 

Right now if you run the routine you cannot manually target anything (when you target someone it will almost instantly detarget)

The main problem i have right now is the erratic behavior it has, sometimes it works sometimes it does not.

Also does BW only have 1 log level? I wanted to run a diagnostic log like i always did for HB.

**Comment by Markeeen** [comment]
[BuddyWing 4196 2016-01-06-09.22.05.txt](https://github.com/BosslandGmbH/BuddyWing.DefaultCombat/files/79606/BuddyWing.4196.2016-01-06-09.22.05.txt)

From what i can tell it targets the wrong guys and heals people who have 100% HP.

**Comment by aevitas** [comment]
> Right now if you run the routine you cannot manually target anything (when you target someone it will almost instantly detarget)

That's definitely something that needs to be looked in to.

> Also does BW only have 1 log level? I wanted to run a diagnostic log like i always did for HB.

No, it provides way more, it's just the UI that isn't able to set them currently - updating the UI is on the list of things to do for BW, this being one of the primary reasons for it.

Judging from the log, we'll probably need to add some logging to get a good idea of when it's clearing its targets, and why.

**Comment by Markeeen** [comment]
Yeah well, the log doesn't provide much. i couldn't even target the tank to set him as one, i paused the routine to set him as tank and after looking into the log it seems the routine was still targeting something because i am pretty sure i didn't set the npc as tank.

I don't even know why he targets the ones he actually is targeting because like i said in the other post, he heals the target even if it's 100%, they aren't set as Tank either.

Looking into the routine doesn't provide a clue either, the settings seems fine.

**Comment by aevitas** [comment]
The unit selection delegate is responsible for the targeting. We could refactor it to make it slightly less obscure, as the `Targeting` class is currently responsible for determining _what_ we should be targeting, but not actually targeting the unit in question.

A quick fix would be to do use an overload that explicitly asks for a `TorCharacter` as one of its parameters, and simply call `.Target()` on it rather than inferring from the BT context.

**Comment by outage12** [comment]
Do you have any updates on healing? I've tried healing on a sorcerer. It will always target someone other than the tank, when the tank is manually clicked it will instantly go back to a different target and continue to heal they target even if the non tank target is at 100% and the tank is at any range of health.

Not trying to come off as pushy, just curious. :)

**Comment by aevitas** [comment]
@outage12 Needs significant work, possibly a rewrite of the whole healing targeting system. It's on the list of things that need fixing.

I don't have a high enough healing character to test this with either, so all the code I can write to address this would be purely theoretical.

**Comment by Wired203** [comment]
This weekend I attempted to tackle this problem.  Initial testing has been good but more testing is required.  I took Pures targeting routine and adapted it to Default Combat.  There were a lot of additional checks in that targeting.  I also found and fixed the set tank bug.  Here's a link to the post.

https://www.thebuddyforum.com/buddy-wing-forum/combat-routines/197829-defaultcombat-94.html#post2173797

**Comment by Wired203** [comment]
So targeting enhancements I made helped and will help in the end,  identified a bug with MaxHealth and other players and posted bug info on Buddywing github.

**Comment by Wired203** [comment]
Healing MaxHealth bug has been fixed,  I have a SVN with code for everyone to test.  Has the Pure code heal targeting which includes group checks etc.  This way you wont heal some random person in zone etc.  Give it a test when you can.

**Comment by Wired203** [comment]
Getting better,  May need to re-write it one more time.  Needs more testing.

**Comment by Wired203** [comment]
Testing is almost completed,  other than when Buddywing was updated it broke healing again 898 is what we are using for testing and everything looks on the up and up.  Below you will find the changes were currently testing.

Healers will attack when they select a mob, otherwise they will heal as normal.
 Changed tank detection routine to make it less spammy for targeting.
 Healers Rejoice, you can now pull mobs and attack when using a grind profile. This wasn't available in the past with Default Combat.
 Rest is fixed to exit in background again, sendkeys no longer works for background
 Tank selection is working as it should. If companion is out he will be tank. If no companion and no tank you will become tank. F12 is fully tested and re-written to work correctly. F12 will set tank if a friendly target is selected. To clear the selection just target either a unfriendly or nothing and hit f12. Bot will then go back to auto Tank selection.
 Added scavenging and bio to corpses.
 Cryo came up with the code for Stims and XP boosts when under 65.
 Dispel is tested but we have very few debuff names in the list. List is found under Helpers/Extensions.cs Public Static Debuff (If anyone has any to add let me know)
 Aoe heals are working, they used melee.dist for their distance checks to fire which was .8f and was changed to it's own float value and 1.2f - Thanks Tiniq
 Removed health logging as it was causing errors/issues
 Thanks to Alltrueist as he has updated quite a few of the routines for healing which were very out of date due to the healing not working for so long.

**Comment by aevitas** [comment]
Impressive! I'm looking forward to the PR for this. :+1:

**Comment by Wired203** [comment]
Posted all changes to GitHub yesterday.

**Comment by pjmagee** [comment]
So is this on your Wired Master branch?

**Comment by pjmagee** [comment]
Can I use it? :)

**Comment by pjmagee** [comment]
Doesnt stop healing someone who is at full HP.

**Comment by Wired203** [comment]
My changes made it into the main branch and had quite a few targeting fixes,  however the bot reports maxhealth at 0 so whichever char is on the top of the list gets healed non stop.  Has been reported but has to be fixed within Buddywing.  When it was working it caused some issues for the solo grinders where they didn't buff correctly since the maxhealth wasn't exactly perfect.

**Comment by pjmagee** [comment]
Lol, many things are broken in Buddywing it's pretty much non-usable.

**Comment by aevitas** [comment]
I've fixed some issues with maximum health a while ago - when did this
break again?

**Comment by Wired203** [comment]
Don't think I had anyone report it working correctly,  to be fair I haven't logged into the game since around the time of my updates.  Got busy with house projects and a 3d printer.  Winter time is the best time to play lots and code :-)
