### ISSUE TITLE
Powertech - Shield Tech CanNotBeDetermined

### ISSUE THREAD

**Issue by Mazriel** [aevitas/BuddyWing.DefaultCombat#2]
Shield Tech discipline is still coming up as CanNotBeDetermined

**Comment by Starbrox** [comment]
Guessing this is kinda the mirror to the vanguard shield specialist so it's the same "bug"? cause it's been a long time since the vanguard was reported....

**Comment by aevitas** [comment]
Yes, this turned out to be something we can't easily fix other than how we're doing it in the rotation factory: https://github.com/BosslandGmbH/BuddyWing.DefaultCombat/blob/master/src/DefaultCombat/Core/RotationFactory.cs#L21

If you could give me the class/advanced class combinations for those two, we could possibly solve it that way.

**Comment by Markeeen** [comment]
Main -> Advanced
 -> Spec

Trooper -> Commando
-> AssaultSpecialist
-> CombatMedic
-> Gunnery

Trooper -> Vanguard
-> Plasmatech
-> ShieldSpecialist
-> Tactics

BountyHunter -> Mercenary
-> Arsenal
-> Bodyguard
-> InnovativeOrdnance

BountyHunter -> PowerTech
 -> AdvancedPrototype
-> Pyrotech
-> ShieldTech

I guess that is what you want?

**Comment by aevitas** [comment]
@Markeeen Yes, thanks. That's one part we use for "correcting" some of the values obtained by the bot's internals. For Shield Tech and Shield Specialist, we're currently using the following spell nodes to identify them:

```
{16141009404323093105, CharacterDiscipline.ShieldTech}, // Jet Charge
{16141074151321389691, CharacterDiscipline.ShieldSpecialist}, // Storm
```

If those are proven wrong (which they obviously are, since you're getting `CanNotBeDetermined`), we can work around that with the class/advanced class/unique spell for discipline combination like we do for some other classes:

```
        if (HasAbility("Flaming Fist") && advancedClass == AdvancedClass.Powertech)
        {
            discipline = CharacterDiscipline.Pyrotech;
            return true;
        }
```

This could work for all classes which are currently not determined properly. Would "Rail Loaders" for shield tech, and "Storm" for shield specialist respectively, work?

ps. Determining disciplines is really, really annoying. :(

**Comment by Markeeen** [comment]
Shield Tech (Bounty Hunter) does have the spell Fire>Storm< but that won't cause problems i guess?

Maybe use the level 10 spells that each specialization gets? They are unique to each spec and will be present as soon as you choose the discipline.

Shield Tech (Bounty Hunter -> Power Tech) = Oil Slick
Shield Specialist (Trooper -> Vanguard) = Riot Gas

**Comment by aevitas** [comment]
@Markeeen Thanks, that should do! I've added the following to the BW core:

```
if (HasAbility("Oil Slick") && advancedClass == AdvancedClass.Powertech)
{
    discipline = CharacterDiscipline.ShieldTech;
    return true;
}

if (HasAbility("Riot Gas") && advancedClass == AdvancedClass.Vanguard)
{
    discipline = CharacterDiscipline.ShieldSpecialist;
    return true;
}
```

And I'll get a new build of the bot out shortly with the combat routine improvements. I'll leave the issue open until we can confirm it's fixed.

**Comment by aevitas** [comment]
@Mazriel Can you confirm this is either still an issue or has been resolved in version 1.0.1256.821? Thanks!

**Comment by Starbrox** [comment]
It's not the "cannotbedetermined" spec anymore :D, looks like it 's working
2016-01-11 09:41:56,731 [7] INFO  Log - User is a BountyHunter
2016-01-11 09:41:58,349 [7] INFO  Log - Advanced Class: Powertech / Discipline: ShieldTech
2016-01-11 09:41:58,349 [7] INFO  Log - Routine Path: Routines
2016-01-11 09:41:59,831 [7] INFO  Log - Medpac  Created!
2016-01-11 09:41:59,863 [7] INFO  Log - [DefaultCombat] Level: 65
2016-01-11 09:41:59,864 [7] INFO  Log - [DefaultCombat] Class: BountyHunter
2016-01-11 09:41:59,864 [7] INFO  Log - [DefaultCombat] Advanced Class: Powertech
2016-01-11 09:41:59,899 [7] INFO  Log - [DefaultCombat] Discipline: ShieldTech
2016-01-11 09:41:59,935 [7] INFO  Log - [DefaultCombat] [Hot Key][F7] Toggle AOE
2016-01-11 09:41:59,935 [7] INFO  Log - [DefaultCombat] [Hot Key][F8] Load UI
2016-01-11 09:41:59,936 [7] INFO  Log - [DefaultCombat] [Hot Key][F12] Set Tank
2016-01-11 09:41:59,936 [7] INFO  Log - [DefaultCombat] Rotation Selected : PowerTech Shieldtech

**Comment by aevitas** [comment]
Great, I'll close the issue then! :+1:
